spring.application.name=Miniuserapi
server.port=8962
spring.datasource.url=jdbc:mysql://localhost:3306/userdb
spring.datasource.username=root
spring.datasource.password=Harsh@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
